
# visdat

<script type="text/javascript">

// toggle visibility of R source blocks in R Markdown output
function toggle_R() {
  var x = document.getElementsByClassName('r');
  if (x.length == 0) return;
  function toggle_vis(o) {
    var d = o.style.display;
    o.style.display = (d == 'block' || d == '') ? 'none':'block';
  }

  for (i = 0; i < x.length; i++) {
    var y = x[i];
    if (y.tagName.toLowerCase() === 'pre') toggle_vis(y);
  }

    var elem = document.getElementById("myButton1");
    if (elem.value === "Hide Code") elem.value = "Show Code";
    else elem.value = "Hide Code";
}

document.write('<input onclick="toggle_R();" type="button" value="Hide Code" id="myButton1"</input>')

</script>

בלה בלה בלה

```{r}
pacman::p_load(
  tidyverse,
  pacman,
  palmerpenguins
)
```


```{r}
visdat::vis_dat(palmerpenguins::penguins_raw)
```
```{r}
visdat::vis_miss(palmerpenguins::penguins_raw)
```



```{r}
palmerpenguins::penguins_raw %>% 
  select(where(is.numeric)) %>% 
  visdat::vis_cor()
```

```{r}
visdat::vis_expect(iris, ~.x %in% c("setosa"))
```
```{r}
visdat::vis_expect(iris, ~.x > 3)
```


